# Generated by Django 6.0.3 on 2026-03-22 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_alter_sucursal_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ítem de checklist',
                'verbose_name_plural': 'Ítems de checklist',
                'db_table': 'checklist_item',
                'ordering': ['pregunta'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'db_table': 'componente',
                'ordering': ['tipo_componente__nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de atributo',
                'verbose_name_plural': 'Tipos de atributo',
                'db_table': 'tipo_atributo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de componente',
                'verbose_name_plural': 'Tipos de componente',
                'db_table': 'tipo_componente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de equipo',
                'verbose_name_plural': 'Tipos de equipo',
                'db_table': 'tipo_equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_patrimonial', models.CharField(max_length=50, unique=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ENTREGADO', 'Entregado'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('OBSERVADO', 'Observado'), ('DADO_DE_BAJA', 'Dado de baja'), ('PERDIDO', 'Perdido')], default='DISPONIBLE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_garantia', models.DateField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='personal.sucursal')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='equipos.tipoequipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
                'ordering': ['codigo_patrimonial'],
            },
        ),
        migrations.CreateModel(
            name='EquipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='equipos.componente')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Componente de equipo',
                'verbose_name_plural': 'Componentes de equipos',
                'db_table': 'equipo_componente',
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.AddField(
            model_name='componente',
            name='tipo_componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='equipos.tipocomponente'),
        ),
        migrations.CreateModel(
            name='TipoEquipoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_equipo', to='equipos.tipoatributo')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atributos', to='equipos.tipoequipo')),
            ],
            options={
                'verbose_name': 'Atributo de tipo de equipo',
                'verbose_name_plural': 'Atributos de tipos de equipo',
                'db_table': 'tipo_equipo_atributo',
                'constraints': [models.UniqueConstraint(fields=('tipo_equipo', 'tipo_atributo'), name='unique_tipo_equipo_atributo')],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_equipo', to='equipos.checklistitem')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_items', to='equipos.tipoequipo')),
            ],
            options={
                'verbose_name': 'Checklist de tipo de equipo',
                'verbose_name_plural': 'Checklists de tipos de equipo',
                'db_table': 'tipo_equipo_checklist',
                'constraints': [models.UniqueConstraint(fields=('tipo_equipo', 'checklist_item'), name='unique_tipo_equipo_checklist')],
            },
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atributos', to='equipos.equipo')),
                ('tipo_atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='equipos.tipoatributo')),
            ],
            options={
                'verbose_name': 'Valor de atributo',
                'verbose_name_plural': 'Valores de atributo',
                'db_table': 'valor_atributo',
                'constraints': [models.UniqueConstraint(fields=('equipo', 'tipo_atributo'), name='unique_valor_atributo_por_equipo')],
            },
        ),
    ]
