# Generated by Django 6.0.3 on 2026-03-22 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='pregunta',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('DADO_DE_BAJA', 'Dado de baja'), ('PERDIDO', 'Perdido')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipocomponente',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='equipos.equipo'),
        ),
        migrations.AlterField(
            model_name='valoratributo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='equipos.equipo'),
        ),
    ]
