# Generated by Django 6.0.3 on 2026-03-27 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('equipos', '0002_alter_checklistitem_pregunta_alter_equipo_estado_and_more'),
        ('mantenimiento', '0002_alter_ticketequipo_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminosCondiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acta', models.CharField(choices=[('ENTREGA', 'Entrega'), ('DEVOLUCION', 'Devolución'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20, unique=True)),
                ('contenido', models.TextField()),
                ('fecha_vigencia', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Términos y condiciones',
                'verbose_name_plural': 'Términos y condiciones',
                'db_table': 'terminos_condiciones',
                'ordering': ['tipo_acta'],
            },
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('ENTREGA', 'Entrega'), ('DEVOLUCION', 'Devolución'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='asignaciones.asignacion')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='mantenimiento.ticketmantenimiento')),
                ('terminos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='actas.terminoscondiciones')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'db_table': 'acta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('gravedad', models.CharField(choices=[('LEVE', 'Leve'), ('GRAVE', 'Grave')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='actas.acta')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencia',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.BooleanField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_checklist', to='actas.acta')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='equipos.checklistitem')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_checklist', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Respuesta de checklist',
                'verbose_name_plural': 'Respuestas de checklist',
                'db_table': 'respuesta_checklist',
                'constraints': [models.UniqueConstraint(fields=('acta', 'equipo', 'checklist_item'), name='unique_respuesta_checklist')],
            },
        ),
    ]
