# Generated by Django 6.0.3 on 2026-03-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminoscondiciones',
            name='tipo_acta',
            field=models.CharField(choices=[('ENTREGA', 'Entrega'), ('DEVOLUCION', 'Devolución'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20),
        ),
    ]
