# Generated by Django 6.0.3 on 2026-04-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0002_alter_terminoscondiciones_tipo_acta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incidencia',
        ),
    ]
