# Generated by Django 6.0.3 on 2026-03-23 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0002_alter_checklistitem_pregunta_alter_equipo_estado_and_more'),
        ('personal', '0002_alter_sucursal_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='personal.empleado')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='personal.sucursal')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'asignacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='asignaciones.asignacion')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Equipo de asignación',
                'verbose_name_plural': 'Equipos de asignación',
                'db_table': 'asignacion_equipo',
                'constraints': [models.UniqueConstraint(fields=('asignacion', 'equipo'), name='unique_equipo_por_asignacion')],
            },
        ),
    ]
