# Generated by Django 6.0.3 on 2026-03-23 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0002_alter_checklistitem_pregunta_alter_equipo_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de mantenimiento',
                'verbose_name_plural': 'Tipos de mantenimiento',
                'db_table': 'tipo_mantenimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TicketMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_mantenimiento', to=settings.AUTH_USER_MODEL)),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='mantenimiento.tipomantenimiento')),
            ],
            options={
                'verbose_name': 'Ticket de mantenimiento',
                'verbose_name_plural': 'Tickets de mantenimiento',
                'db_table': 'ticket_mantenimiento',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TicketEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_mantenimiento', to='equipos.equipo')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='mantenimiento.ticketmantenimiento')),
            ],
            options={
                'verbose_name': 'Equipo en ticket',
                'verbose_name_plural': 'Equipos en tickets',
                'db_table': 'ticket_equipo',
                'constraints': [models.UniqueConstraint(fields=('ticket', 'equipo'), name='unique_ticket_equipo')],
            },
        ),
    ]
