# Generated by Django 6.0.3 on 2026-04-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_alter_ticketequipo_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmantenimiento',
            name='solucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
