# Generated by Django 6.0.3 on 2026-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_ticketmantenimiento_solucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketequipo',
            name='estado_anterior',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('DADO_DE_BAJA', 'Dado de baja'), ('PERDIDO', 'Perdido')], max_length=20, null=True),
        ),
    ]
